channels:
  - conda-forge
dependencies:
  - dask=2022.8.1
  - dask-cuda=22.8.0
  - dask-labextension=5.2.0
  - einops=0.4.1
  - fastai=1.0.61
  - fsspec=2022.3.0
  - graphviz=0.20
  - holoviews=1.14.9
  - hvplot=0.8.0
  - imageio=2.19.3
  - ipykernel=6.13.0
  - ipyleaflet=0.13.6
  - ipywidgets=7.7.0
  - jupyterlab=3.4.5
  - numba=0.55.1
  - numpy=1.21.6
  - nvidia-ml-py3=7.352.0
  - opencv-python=4.5.5.64
  - pandas=1.4.2
  - panel=0.13.0
  - python=3.9
  - rioxarray=0.11.1
  - scikit-image=0.19.2
  - stac_vrt=1.0.3
  - xarray=2022.3.0
  - xarray-spatial=0.3.5
