#!/bin/bash
mkdir catalogs
mkdir catalogs/17_05
mkdir catalogs/22_05
~/.local/bin/gdown 1JoT5pCLUC2RHcGvj4TzqTL-WmmjbASRy -O catalogs/17_05/mosaic.tif
~/.local/bin/gdown 1tPR4udbM9KCFJOBzyJdwrLaA1RPeCDXg -O catalogs/22_05/mosaic.tif
